input productUpdatableFields {
  name: String
  price: Float
  description: String
  images_url: [String!]
  category: String
  sizes: [String!]
  colors: [String!]
  stock: Int
  numberOfLikes: Int
  numberOfSales: Int
  searchTags: [String!]
}

input productCreateFields {
  name: String!
  price: Float!
  description: String
  imagesUrl: [String!]!
  category: String!
  sizes: [String!]
  colors: [String!]
  stock: Int!
  searchTags: [String!]!
}

type Product {
  id: ID!
  name: String!
  price: Float!
  description: String
  imagesUrl: [String!]!
  category: String!
  sizes: [String!]
  colors: [String!]
  stock: Int!
  searchTags: [String!]!

  # authors: [User!]!
  createdAt: String!
  updatedAt: String!
  numberOfLikes: Int!
  numberOfSales: Int!
}

type deleteResponse {
  message: String
  code: Int!
  success: Boolean!
}

type Query {
  getProduct(id: ID!): Product
  getProducts: [Product!]!
}

type Mutation {
  createProduct(productCreateFields: productCreateFields!): Product!
  updateProduct(
    id: ID!
    productUpdatableFields: productUpdatableFields!
  ): Product
  deleteProduct(id: ID!): deleteResponse!
}
