input userUpdatableFields {
  name: String
  email: String
  password: String
  avatarUrl: String
}

type User {
  id: ID!
  name: String!
  email: String!
  avatarUrl: String!
  token: String
  createdAt: String!
  updatedAt: String!
}

type Query {
  getUser(id: ID!): User
  getUsers: [User!]!
}

type Mutation {
  updateUser(id: ID!, userUpdatableFields: userUpdatableFields!): User!
  deleteUser(id: ID!): deleteResponse!
}
