input updatableUserFields {
  name: String
  email: String
  password: String
  avatar_url: String
}

type User {
  authId: ID!
  name: String
  email: String
  avatarUrl: String
  createdAt: String
  lastLogin: String
}

type Query {
  getUser(id: ID!): User
  getUsers: [User!]!
}

type Mutation {
  createUser(name: String!, email: String!, password: String!): String! # returns id of created user or error message
  updateUser(id: ID!, updatableUserFields: updatableUserFields!): User
  deleteUser(id: ID!): String! # returns id of deleted user or error message
}
